---
title: "Analysis"
output: html_document
---

```{r libraries}

library(tidyverse)

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data}

f <- read.csv(file = '../Parser/output/backup/method_chaining_results.csv')
f_with_test <- read.csv(file = "../Parser/output/method_chaining_results_with_test_and_nontest.csv")
classified <- read.csv(file = "../parser/output/binned_size_chain_classification_counts.csv")
manual_insp <- read.csv(file = "Manual_Inspection.csv")
lines_of_code <- read.csv(file = "lines_of_code.csv")
```

```{r f clean data}

f <- f[!(f$LongestChain == -1),]
```

```{r f_with_test clean data}
f_with_test <- f_with_test[!is.nan(f_with_test$LongestChain),]
f_with_test <- f_with_test[,1:348]
f_with_test[is.na(f_with_test)] <- 0
f_with_test <- f_with_test[-1475,]  
```

```{r classified clean data}

classified$Others <- classified$Assertion
classified$Assertion <- classified$Builder
classified$Builder <- classified$Accessor
classified$Accessor <- classified$Size
classified$Size <- NULL
```

```{r relative_occurrence (fn)}

relative_occurrence <- f

relative_occurrence[ , 5:403] <- f[ , 5:403] / f[ , 4]

relative_occurrence <- select(relative_occurrence, -LongestChain, -Length.0, -Length.1)

```

```{r clean relative_occurrence}

relative_occurrence <- relative_occurrence[!(is.nan(relative_occurrence$Length.2) | relative_occurrence$Length.2 == Inf), ]

```

```{r fn}

fn <- data.frame(row.names = c(1:400))
fn$n <- c(1:400)
#fn$count <- c(2:400)
fn$relative_occurrence <- c(1:400)

for(i in 1:nrow(fn)) {
  #fn[i,1] <- sum(na.omit(f[, i + 4]))
  fn[i,2] <- mean(na.omit(relative_occurrence[, i]))
}

fn <- fn[-1,]

```

```{r plot fn}
p <- ggplot(fn, aes(n, relative_occurrence))
p + geom_point() + scale_y_log10() + scale_x_log10()
```

```{r ratio}

ratio <- f
ratio <- select(ratio, Repo)

ratio$r <- f[ , 3]
for(i in 0:nrow(ratio)) {
  ratio[i, 2] <- sum(f[i, 5:403]) / sum(f[i, 4:403])  
}
```

```{r ratio histogram}

a <- ggplot(ratio, aes(x = r))

a + geom_histogram(color = "black", fill = "red")

```

```{r mc_bins}
mc_binned <- data.frame(row.names = c("Short", "Long", "ExtLong"))
mc_binned$num_chains_2019_2020 <- c(sum(f[,5:11]), sum(f[,12:44]), sum(f[,45:403]))
```

```{r relative_occurrence_tests (fn)}

relative_occurrence_tests <- f_with_test

relative_occurrence_tests[ , 6:348] <- f_with_test[ , 6:348] / f_with_test[ , 5]

relative_occurrence_tests <- select(relative_occurrence_tests, -LongestChain, -Length.0, -Length.1)

relative_occurrence_tests[is.na(relative_occurrence_tests)] = 0

```

```{r normalize_data def}
normalize_data <- function(data)
{

  for(i in 1:dim(data)[1])
  {
    total <- sum(data[i,])
    if(total == 0)
      next

    for(k in 1:range(length(data[i,])))
    {
      data[i,k] <- data[i,k] / total
    }
  }
  
  return(data);  
}
```

```{r scale classified data}
classified_scaled <- normalize_data(classified)
classified_scaled
```

```{r bin manual_inspection}

manual_insp_binned <- data.frame(row.names=c("S","L","XL"))
manual_insp_binned$Accessors <- c(sum(manual_insp$non.test..Short..Accessor, manual_insp$test..Short..Accessor), sum(manual_insp$non.test..Long..Accessor, manual_insp$non.test..Long..Accessor), sum(manual_insp$test..ExtLong..Accessor, manual_insp$non.test..ExtLong..Accessor))

manual_insp_binned$Builders <- c(sum(manual_insp$non.test..Short..Builder, manual_insp$test..Short..Builder), sum(manual_insp$non.test..Long..Builder, manual_insp$non.test..Long..Builder), sum(manual_insp$test..ExtLong..Builder, manual_insp$non.test..ExtLong..Builder))

manual_insp_binned$Assertion <- c(sum(manual_insp$non.test..Short..Assertion, manual_insp$test..Short..Assertion), sum(manual_insp$non.test..Long..Assertion, manual_insp$non.test..Long..Assertion), sum(manual_insp$test..ExtLong..Assertion, manual_insp$non.test..ExtLong..Assertion))

manual_insp_binned$Others <- c(sum(manual_insp$non.test..Short..Others, manual_insp$test..Short..Others), sum(manual_insp$non.test..Long..Others, manual_insp$non.test..Long..Others), sum(manual_insp$test..ExtLong..Others, manual_insp$non.test..ExtLong..Others))

manual_insp_binned
```

```{r scale_binned_manual_inspection}
manual_insp_binned <- normalize_data(manual_insp_binned)
manual_insp_binned
```


```{r find repos with longest chains}
S_bin <- f %>% filter(f$LongestChain > 1 & f$LongestChain <= 8)
S_bin
L_bin <- f %>% filter(f$LongestChain > 8 & f$LongestChain < 42)
L_bin
XL_bin <- f %>% filter(f$LongestChain >= 42)
XL_bin[order(XL_bin$LongestChain, decreasing = TRUE),]
f %>% filter(f$LongestChain >= 100)
f %>% filter(f$LongestChain >= 200)
f %>% filter(f$LongestChain >= 300)


```

```{r bin_stats funct}
bin_stats <- function(bin, bin_lower, bin_upper) {
  tmp <- bin[, bin_lower:bin_upper]
  tmp <- colSums(tmp, na.rm = TRUE)
  tmp_pop <- sum(tmp)
  tmp_mu <- sum(colSums(bin[,5:bin_upper]) * seq(2,bin_upper-3)) / sum(bin[,5:bin_upper])
  tmp_bin_mu <- sum(tmp * seq(bin_lower-3,bin_upper-3)) / sum(tmp)
  
  tmp_bin_sd <- 0
  for(i in 1:length(tmp)) {
        tmp_bin_sd <- tmp_bin_sd + ((bin_lower - 4 + i - tmp_bin_mu))^2 * tmp[i]
  }
  tmp_bin_sd <- tmp_bin_sd / tmp_pop
  
  tmp_sd <- 0
  for(i in 5:bin_upper) {
        tmp_sd <- tmp_sd + ((i - 3 - tmp_mu))^2 * sum(bin[,i])
  }
  tmp_sd <- tmp_sd / sum(colSums(bin[,5:bin_upper]))
  
  tmp_ratio <- dim(bin)[1] / dim(f)[1]
  return(c(tmp_ratio, dim(bin)[1], tmp_mu,  tmp_bin_mu, sqrt(tmp_sd), sqrt(tmp_bin_sd)))
}

size_bins <- data.frame(row.names = c("repo_count_ratio", "repo_count", "mean_chain_length", "bin_mean_chain_length", "chain_length_sd", "bin_chain_length_sd"))
size_bins$S <- bin_stats(S_bin, 5, 11)
size_bins$L <- bin_stats(L_bin, 12, 45)
size_bins$xL <- bin_stats(XL_bin, 46, 403)
size_bins <- data.frame(t(size_bins))
size_bins$size_id <- row.names(size_bins)
size_bins
```

```{r size_bins plots}

bin_ratio_plot <- ggplot(size_bins, aes(x=size_id, y=repo_count_ratio))

bin_ratio_plot + geom_bar(stat="identity", color="black", fill=c("blue","green","red"))

size_id <-rep(size_bins$size_id,2)
mean_type <- c(rep("total_mean", 3), rep("bin_mean",3))
mean_val <- c(size_bins$mean_chain_length, size_bins$bin_mean_chain_length)

bin_stat <- data.frame(size_id,type,val)
ggplot(bin_stat, aes(fill=mean_type, y=mean_val, x=size_id)) + geom_bar(position="dodge", stat="identity")

bin_stat$sd_type <- c(rep("total_sd", 3), rep("bin_sd", 3))
bin_stat$sd_val <- c(size_bins$chain_length_sd, size_bins$bin_chain_length_sd)

ggplot(bin_stat, aes(fill=sd_type, y=sd_val, x=size_id)) + geom_bar(position="dodge", stat="identity")

```

```{r classified_size_bins plots}

size_id <-rep(size_bins$size_id,4)
method_type <- c(rep("Accessor", 3), rep("Builder",3), rep("Assertion", 3), rep("Others", 3))

within_size_bin_chain_ratio <- c(classified_scaled$Accessor, classified_scaled$Builder, classified_scaled$Assertion, classified_scaled$Others)

classified_bins <- data.frame(size_id,method_type,within_size_bin_chain_ratio)
classified_bins

ggplot(classified_bins, aes(fill=method_type, y=within_size_bin_chain_ratio, x=size_id)) + geom_bar(position="dodge", stat="identity")

```

```{r manual_inspected_bin plots}
size_id <-rep(size_bins$size_id,4)
method_type <- c(rep("Accessor", 3), rep("Builder",3), rep("Assertion", 3), rep("Others", 3))

within_size_bin_chain_ratio <- c(manual_insp_binned$Accessor, manual_insp_binned$Builder, manual_insp_binned$Assertion, manual_insp_binned$Others)

manual_classified_bins <- data.frame(size_id,method_type,within_size_bin_chain_ratio)
manual_classified_bins

ggplot(manual_classified_bins, aes(fill=method_type, y=within_size_bin_chain_ratio, x=size_id)) + geom_bar(position="dodge", stat="identity")
```

```{r fn_with_tests}

fn_with_tests <- data.frame(row.names = c(1:684))
#fn$count <- c(2:400)
fn_with_tests$relative_occurrence <- c(1:684)
fn_with_tests$file_type <- seq(1,684)
fn_with_tests$chain_length <- rep(1:342, each=2)

fn_with_tests$file_type <- rep(c("Non-Test", "Test"), 342)

for(i in 1:nrow(fn_with_tests)) {
  #fn[i,1] <- sum(na.omit(f[, i + 4]))
  if(fn_with_tests$file_type[i] == "Non-Test")
  {
    fn_with_tests[i,1] <- mean(na.omit(relative_occurrence_tests[seq(1, nrow(relative_occurrence_tests), by=2), fn_with_tests$chain_length[i] + 3]))
  }
  else if(fn_with_tests$file_type[i] == "Test")
  {
    fn_with_tests[i,1] <- mean(na.omit(relative_occurrence_tests[seq(2, nrow(relative_occurrence_tests), by=2), fn_with_tests$chain_length[i] + 3]))
  }
}

#fn_with_tests <- fn_with_tests[-1,]
```

```{r plot fn_with_tests}
p <- ggplot(fn_with_tests, aes(x = chain_length, y = relative_occurrence, color = file_type))
p + geom_point() + scale_y_log10() + scale_x_log10()
```

```{r ratio_with_tests}

ratio_with_tests <- f_with_test
ratio_with_tests <- select(ratio_with_tests, Repo, File_Type)
ratio_with_tests$r <- f_with_test[ , 3]

ratio_with_tests$r[is.na(ratio_with_tests$r)] <- 0.0

for(i in 1:nrow(ratio_with_tests)) {
  denominator <- sum(f_with_test[i, 5:ncol(f_with_test)])
  
  if(denominator == 0)
  {
    ratio_with_tests[i,3] <- 0.0
  }
  else
  {
    ratio_with_tests[i,3] <- sum(f_with_test[i, 6:ncol(f_with_test)]) / denominator  
  }
            
}

```

```{r ratio_with_tests histogram}


ratio_with_tests$r <- as.numeric(ratio_with_tests$r)

a <- ggplot(ratio_with_tests, aes(x = r,  color = File_Type))

a + geom_histogram(binwidth= 0.01, fill = "white", alpha=0.4, position = "identity") + scale_y_log10()

```

```{r ratio_with_test means}
{
  test_r <- as.numeric(ratio_with_tests$r[ratio_with_tests$File_Type == "T"])
  mean(non_test_r)
  
  non_test_r <- as.numeric(ratio_with_tests$r[ratio_with_tests$File_Type == "NT"])
  mean(non_test_r)
}